source "https://rubygems.org"

gem "puma", ">= 5.0"
gem "rails", "~> 7.2.3"
gem "sqlite3", ">= 1.4"

gem "tzinfo-data", platforms: %i[windows jruby]

gem "bootsnap", require: false

gem "devise", "~> 5.0"

gem "faraday", "~> 2.14"
gem "faraday-httpclient"
gem "faraday-retry"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false

  gem "rspec-rails", "~> 8.0.0"
end

group :test do
  gem "webmock"
end

group :development do
  gem "annotate", "~> 3.2"
end
