Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyElse:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
